/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.22                          *
 *        Compiled Jul  4 2013, 15:16:01                              *
 *        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0            (GUI_ID_USER + 0x1A)
#define ID_SPINBOX_0            (GUI_ID_USER + 0x1B)
#define ID_SPINBOX_1            (GUI_ID_USER + 0x1C)
#define ID_SPINBOX_2            (GUI_ID_USER + 0x1D)
#define ID_TEXT_DAY            (GUI_ID_USER + 0x1E)
#define ID_TEXT_MONTH            (GUI_ID_USER + 0x1F)
#define ID_TEXT_YEAR            (GUI_ID_USER + 0x20)
#define ID_SPINBOX_3            (GUI_ID_USER + 0x21)
#define ID_SPINBOX_4            (GUI_ID_USER + 0x22)
#define ID_TEXT_HOUR            (GUI_ID_USER + 0x23)
#define ID_TEXT_MINUTES            (GUI_ID_USER + 0x24)
#define ID_BUTTON_OK            (GUI_ID_USER + 0x25)

// USER START (Optionally insert additional defines)

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = { {
		FRAMEWIN_CreateIndirect, "DateTime", ID_FRAMEWIN_0, 56, 45, 208, 150, 0,
		0x0, 0 }, { SPINBOX_CreateIndirect, "Day", ID_SPINBOX_0, 27, 40, 37, 20,
		0, 0x0, 0 }, { SPINBOX_CreateIndirect, "Month", ID_SPINBOX_1, 73, 40,
		37, 20, 0, 0x0, 0 }, { SPINBOX_CreateIndirect, "Year", ID_SPINBOX_2,
		119, 40, 49, 20, 0, 0x0, 0 }, { TEXT_CreateIndirect, "DayText",
		ID_TEXT_DAY, 27, 20, 31, 18, 0, 0x64, 0 }, { TEXT_CreateIndirect,
		"MonthText", ID_TEXT_MONTH, 70, 20, 31, 18, 0, 0x64, 0 }, {
		TEXT_CreateIndirect, "YearText", ID_TEXT_YEAR, 119, 20, 31, 18, 0, 0x64,
		0 }, { SPINBOX_CreateIndirect, "Hour", ID_SPINBOX_3, 27, 90, 37, 20, 0,
		0x0, 0 }, { SPINBOX_CreateIndirect, "Minutes", ID_SPINBOX_4, 73, 90, 37,
		20, 0, 0x0, 0 }, { TEXT_CreateIndirect, "HourText", ID_TEXT_HOUR, 27,
		70, 37, 18, 0, 0x64, 0 }, { TEXT_CreateIndirect, "MinutesText",
		ID_TEXT_MINUTES, 74, 70, 41, 18, 0, 0x64, 0 }, { BUTTON_CreateIndirect,
		"OKButton", ID_BUTTON_OK, 125, 83, 52, 27, 0, 0x0, 0 }, };

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int NCode;
	int Id;

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'DayText'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_DAY);
		TEXT_SetText(hItem, "Day");
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'MonthText'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MONTH);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		TEXT_SetTextColor(hItem, 0x00000000);
		TEXT_SetText(hItem, "Month");
		//
		// Initialization of 'YearText'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_YEAR);
		TEXT_SetText(hItem, "Year");
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'HourText'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HOUR);
		TEXT_SetText(hItem, "Hour");
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'MinutesText'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MINUTES);
		TEXT_SetText(hItem, "Minutes");
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'OKButton'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
		BUTTON_SetText(hItem, "OK");
		WM_MakeModal(pMsg->hWin);
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_SPINBOX_0: // Notifications sent by 'Day'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_MOVED_OUT:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				break;
			}
			break;
		case ID_SPINBOX_1: // Notifications sent by 'Month'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_MOVED_OUT:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				break;
			}
			break;
		case ID_SPINBOX_2: // Notifications sent by 'Year'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_MOVED_OUT:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				break;
			}
			break;
		case ID_SPINBOX_3: // Notifications sent by 'Hour'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_MOVED_OUT:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				break;
			}
			break;
		case ID_SPINBOX_4: // Notifications sent by 'Minutes'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_MOVED_OUT:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				break;
			}
			break;
		case ID_BUTTON_OK: // Notifications sent by 'OKButton'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				SetDateTime(pMsg->hWin);
				GUI_EndDialog(pMsg->hWin, 0);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		}
		break;
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateDateTime
 */
WM_HWIN CreateDateTime(void);
WM_HWIN CreateDateTime(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate),
			_cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

/*************************** End of file ****************************/
