/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.22                          *
 *        Compiled Jul  4 2013, 15:16:01                              *
 *        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
// USER END
#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x0C)
#define ID_DROPDOWN_LIGHTS     (GUI_ID_USER + 0x0E)
#define ID_TEXT_ADDRESS     (GUI_ID_USER + 0x0F)
#define ID_TEXT_ONOFF     (GUI_ID_USER + 0x10)
#define ID_BUTTON_ONOFF     (GUI_ID_USER + 0x11)
#define ID_TEXT_MODE     (GUI_ID_USER + 0x13)
#define ID_BUTTON_MODE     (GUI_ID_USER + 0x14)
#define ID_BUTTON_ADD     (GUI_ID_USER + 0x16)
#define ID_BUTTON_RECONFIGURE     (GUI_ID_USER + 0x17)
#define ID_BUTTON_REMOVE     (GUI_ID_USER + 0x18)
#define ID_BUTTON_OK     (GUI_ID_USER + 0x27)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END
/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = { {
		FRAMEWIN_CreateIndirect, "ManageLights", ID_FRAMEWIN_0, 10, 30, 300,
		190, 0, 0x0, 0 }, { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_LIGHTS,
		8, 8, 80, 19, 0, 0x0, 0 }, { TEXT_CreateIndirect, "Text",
		ID_TEXT_ADDRESS, 107, 10, 117, 16, 0, 0x64, 0 }, { TEXT_CreateIndirect,
		"Text", ID_TEXT_ONOFF, 108, 32, 80, 20, 0, 0x64, 0 }, {
		BUTTON_CreateIndirect, "Button", ID_BUTTON_ONOFF, 98, 75, 80, 20, 0,
		0x0, 0 }, { TEXT_CreateIndirect, "Text", ID_TEXT_MODE, 107, 52, 80, 20,
		0, 0x64, 0 }, { BUTTON_CreateIndirect, "Button", ID_BUTTON_MODE, 195,
		75, 80, 20, 0, 0x0, 0 }, { BUTTON_CreateIndirect, "Button",
		ID_BUTTON_ADD, 10, 101, 80, 20, 0, 0x0, 0 }, { BUTTON_CreateIndirect,
		"Button", ID_BUTTON_RECONFIGURE, 11, 126, 80, 20, 0, 0x0, 0 }, {
		BUTTON_CreateIndirect, "Button", ID_BUTTON_REMOVE, 12, 150, 80, 20, 0,
		0x0, 0 }, { BUTTON_CreateIndirect, "OK", ID_BUTTON_OK, 196, 131, 80, 20,
		0, 0x0, 0 },
// USER START (Optionally insert additional widgets)
// USER END
		};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END
/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int NCode;
	int Id;

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Dropdown'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_LIGHTS);
		DROPDOWN_AddString(hItem, "Light 2");
		DROPDOWN_AddString(hItem, "Light 1");
		DROPDOWN_AddString(hItem, "Item");
		DROPDOWN_IncSel(hItem);
		//
		// Initialization of 'Address' Text
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ADDRESS);
		TEXT_SetText(hItem, "Address: <address>");
		//
		// Initialization of 'Status' Text
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ONOFF);
		TEXT_SetText(hItem, "Status: ON");
		//
		// Initialization of 'On/Off' Button
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ONOFF);
		BUTTON_SetText(hItem, "Toggle On/Off");
		//
		// Initialization of 'Mode' Text
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MODE);
		TEXT_SetText(hItem, "Mode: Auto");
		//
		// Initialization of 'Mode' Button
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_MODE);
		BUTTON_SetText(hItem, "Toggle Auto");
		//
		// Initialization of 'Add' Button
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ADD);
		BUTTON_SetText(hItem, "Add new...");
		//
		// Initialization of 'Reconfigure' Button
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RECONFIGURE);
		BUTTON_SetText(hItem, "Reconfigure...");
		//
		// Initialization of 'Remove' Button
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_REMOVE);
		BUTTON_SetText(hItem, "Remove...");

		WM_MakeModal(pMsg->hWin);
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_DROPDOWN_LIGHTS: // Notifications sent by 'Dropdown'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				break;
			}
			break;
		case ID_BUTTON_ONOFF:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				ToggleLightN(1, WM_GetDialogItem(pMsg->hWin, ID_TEXT_ONOFF));
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_MODE:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				ToggleLightModeN(1, WM_GetDialogItem(pMsg->hWin, ID_TEXT_MODE));
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_ADD:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				AddNewLight(0);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_RECONFIGURE:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				ReconfigureLight(0);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_REMOVE:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				RemoveLight(0);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_OK:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				GUI_EndDialog(pMsg->hWin, 0);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		}
		break;
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateManageLights
 */
WM_HWIN CreateManageLights(void);
WM_HWIN CreateManageLights(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate),
			_cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}


/*************************** End of file ****************************/
